pipeline {
    agent any
    environment {
        // Define your vars
        NAME = 'Deamann'
    }

    stages {

        stage('Login to Docker Hub') {
            steps {
                sh "cat passwd | docker login -u profftimothy@gmail.com --password-stdin"
                echo 'Login successfully'
            }
        }

        stage('Build Docker Image') {
            steps {
                // Building stage
                echo "Welcome to ${NAME}'s Jenkins World"
                sh '''
                docker build . -t deamann/projectz:v1
                '''
                echo "The Build URL is ${BUILD_URL}"
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                sh '''
                docker push deamann/projectz:v1
                '''
            }
        }

        stage('Test') {
            steps {
                sh "docker images"
            }
        }

        stage('Run the Image on K8s Cluster') {
            steps {
                sh '''
                kubectl apply -f ./serviceapp_deployment
                kubectl get pods
                kubectl get deploy
                '''
            }
        }

        stage('Confirm Deployment is Running') {
            steps {
                sh '''
                kubectl get po,svc,deployment
                '''
            }
        }
    }

    post {
        success {
            // Actions to perform when the pipeline is successful
            echo "DevOps Project... Hurrah! Build ${BUILD_ID} was successful!"
        }
        failure {
            echo "Pipeline failed... Oooops"
        }
    }
}
