apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectz-deployment
  labels:
    app: serviceapp
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: serviceapp
  template:
    metadata:
      labels:
        app: serviceapp
    spec:
      containers:
      - name: serviceapp
        image: deamann/projectz:v1 
        ports:
        - containerPort: 3000 
---
apiVersion: v1
kind: Service
metadata:
  name: projectz-service
  labels:
    app: serviceapp
spec:
  selector:
    app: serviceapp
  ports:
  - protocol: TCP
    port: 3000          # Service port
    targetPort: 3000  # Container's exposed port
  type: NodePort  # Can be ClusterIP, NodePort, or LoadBalancer based on your use case

